# This is a basic workflow to help you get started with Actions

name: tox-test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events, or push events to master branch
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tox-test"
  tox-test:
    # The type of runner that the job will run on
    runs-on: 'ubuntu-latest'
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental:
          - false
        task:
          - 'test'
        python-version:
          - '2.7'
          - 'pypy2'
          - '3.5'
          - 'pypy3'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        include:
          - python-version: '3.9'
            task: 'coverage'
            experimental: false
          - python-version: '3.9'
            task: 'lint'
            experimental: false
          - python-version: '3.10-dev'
            task: 'test'
            experimental: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # GitHub Actions checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        if: ${{ matrix.task == 'test' }}
        run: tox

      - name: 'Run coverage'
        if: ${{ matrix.task == 'coverage' }}
        run: tox -e cover-all
      - name: 'Report coverage'
        if: ${{ matrix.task == 'coverage' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tox -e coveralls-gh-actions

      - name: 'Run linter'
        if: ${{ matrix.task == 'lint' }}
        run: tox -e pyflakes
